FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl

#///////////////////////////////
# Add crontab file in the cron directory
ADD crontab /etc/cron.d/hello-cron

# # Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/hello-cron

# # Create the log file to be able to run tail
RUN touch /var/log/cron.log

#Install Cron
RUN apt-get update
RUN apt-get -y install cron

CMD cron && tail -f /var/log/cron.log